# Generated by Django 5.1.4 on 2026-06-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_sale_cash_received_sale_change_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('RENT', 'Alquiler'), ('SERVICES', 'Servicios'), ('INVENTORY', 'Reposición de Inventario'), ('SALARY', 'Sueldos'), ('TAXES', 'Impuestos'), ('MARKETING', 'Marketing'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Varios')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
