# Generated by Django 5.1.4 on 2026-06-08 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_count', models.IntegerField(default=0)),
                ('fiado_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-date'],
            },
        ),
    ]
