# Generated by Django 5.1.4 on 2026-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_cashclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('frequency_hours', models.IntegerField(default=24)),
                ('max_backups', models.IntegerField(default=10)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('backup_folder', models.CharField(default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuración de Backup',
            },
        ),
    ]
