# Generated by Django 5.1.4 on 2026-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_backupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='installation_uuid',
            field=models.CharField(blank=True, default='', max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='max_remote_backups',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='supabase_bucket',
            field=models.CharField(default='fiadoapp-backups', max_length=128),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='supabase_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
