# Generated by Django 5.1.4 on 2026-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_backupconfig_installation_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
