# Generated by Django 5.1.4 on 2026-06-29 07:37

from django.db import migrations


def backfill_cost_at_sale(apps, schema_editor):
    SaleItem = apps.get_model('coreApp', 'SaleItem')
    for item in SaleItem.objects.filter(cost_at_sale=0).select_related('product'):
        item.cost_at_sale = item.product.cost
        item.save(update_fields=['cost_at_sale'])


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_saleitem_cost_at_sale'),
    ]

    operations = [
        migrations.RunPython(backfill_cost_at_sale, migrations.RunPython.noop),
    ]
