# Generated by Django 5.1.4 on 2026-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_backfill_cost_at_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='La Tiendita', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
    ]
